% include path
ipath = ['-I' '../../include'];


% src path
src_path = '../';
mex ('-v','-largeArrayDims',...
    'equalitySampling.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');
mex ('-v','-largeArrayDims',...
    'diamondSampling.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');
mex ('-v','-largeArrayDims',...
    'wedgeSampling.cpp',...
    [src_path,'tensor.cpp'],ipath, ...
    '-outdir','../../bin');
mex ('-v','-largeArrayDims',...
    'diamondTensor.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');
mex ('-v','-largeArrayDims',...
    'wedgeTensor.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');
mex ('-v','-largeArrayDims',...
    'querySampling.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');
mex ('-v','-largeArrayDims',...
    'querySampling.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');