% mex
mex ('-v','-largeArrayDims',...
    'fullSampling.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'extensionSampling.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'centralSampling.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'diamondSampling.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'wedgeSampling.cpp',...
    [src_path,'tensor.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'diamondTensor.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'wedgeTensor.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'querySampling.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'queryEqualitySampling.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);    
mex ('-v','-largeArrayDims',...
    'queryExtensionSampling.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
