mex ('-v','-largeArrayDims',...
    'datareduce.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'merge.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);
