mex ('-v','-largeArrayDims',...
    'factorization.cpp',['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'trainFashion.cpp',['-I',ipath], ...
    '-outdir',bin_path);
mex ('-v','-largeArrayDims',...
    'testrandom.cpp',...
    [src_path,'matrix.cpp'],['-I',ipath], ...
    '-outdir',bin_path);