% include path
ipath = ['-I' '../../include'];
src_path = '../';
mex ('-v','-largeArrayDims',...
    'diamond_matrix.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');
mex ('-v','-largeArrayDims',...
    'wedge_matrix.cpp',...
    [src_path,'matrix.cpp'],ipath, ...
    '-outdir','../../bin');