path = pwd;
ipath = fullfile(path,'include');
src_path = fullfile(path,'src/');
bin_path = fullfile(path,'bin');
addpath(bin_path);
cd ./src; make;
cd ./TensorCP; make;
cd ../MatrixMul ; make;
cd ../ExactSearch ; make;
cd ../../;