data = 'data\';
movielens = [data 'hetrec2011-movielens-2k-v2\'];
lastfm = [data 'hetrec2011-lastfm-2k\'];
merge_data([movielens 'user_ratedmovies-timestamps.dat'],...
    [movielens 'user_taggedmovies-timestamps.dat'],...
    'movielens.dat');
merge_data([lastfm 'user_artists.dat'],...
    [lastfm 'user_taggedartists-timestamps.dat'],...
    'lastfm.dat');